@ECHO off

:: 变量定义
SET SERVER_ID=%1
SET NODE_ID=%2
SET IP=192.168.1.242
SET NODE_BASE=vt_dev
SET STOP_NODE_BASE=vt_stop
SET COOKIE=vt_dev

:: 动态变量
IF %NODE_ID% EQU 10 (
    SET NODE_NAME=%NODE_BASE%_s%SERVER_ID%@%IP%
	SET NODE_TITLE=s%SERVER_ID%
	SET STOP_NODE_NAME=%STOP_NODE_BASE%_s%SERVER_ID%@%IP%
	SET STOP_TITLE=stop_s%SERVER_ID%
	SET COOKIE=%COOKIE%_s%SERVER_ID%
) ELSE (
	SET NODE_NAME=%NODE_BASE%_k%NODE_ID%@%IP%
	SET NODE_TITLE=k%NODE_ID%
	SET STOP_NODE_NAME=%STOP_NODE_BASE%_k%NODE_ID%@%IP%
	SET STOP_TITLE=stop_k%NODE_ID%
	SET COOKIE=%COOKIE%_kf
)

:: 设置标题
TITLE %STOP_TITLE%

:: 启动节点
CD ../
erl -noshell -name %STOP_NODE_NAME% -setcookie %COOKIE% -pa ebin -eval "rpc:call('%NODE_NAME%', game, stop, [])" -s init stop
TASKKILL /F /FI "WINDOWTITLE eq %NODE_TITLE%"
TASKKILL /F /FI "WINDOWTITLE eq %NODE_TITLE%"
TASKKILL /F /FI "WINDOWTITLE eq %STOP_TITLE%"
TASKKILL /F /FI "WINDOWTITLE eq %STOP_TITLE%"